language: node_js
node_js:
  - 12
install:
  - npm install
script:
  - echo "skipping tests"
deploy:
  app: stackpond-ethereum-explorer
  provider: heroku
  api_key:
    secure: RiJnCdayXOZd7IN/ZB74VSNrwa30QFt50dBDth6tz6CsL7w4E44EpeIDX9QD3MN78X5286HJfh49xGcXkQ/PfPPXoe4sbq/nRoSJqd18mTR1+tc3OqEosed2w+jfhuYC9J/qCICbhXVopc6+sXYfC18B4xmSR7VETDZupw2jJz59u6hHduAunYNm7pUfySzedAd3I0PMd8rAuimmg0RhmzSkSh7Usl5oYI0MYqhIXsXwnAjNTtdOBvece1qPWj2Yf885UW0iyazBL7rO8NwRHz5MtePMIWB/U0XFmCMPNpWwNI0YGlCGsrxwNuF6Ls41EqWM+Sp0Tsmyk3RWD0aMhTwGJjL9wFFZwmZD9MW7leDtUq0atqqdwKrAj2MzdGvF2+8umkSOizXseUWm6p14JJxC4l2HYKeJNW7bO8Mfpm2qIsS0uQLjkzICS6d7btsfRans3Cttwwsb21Hd3xP0Ba71NaZ2823+ncvALS2a5ZQFGViC4/8CCa6HHSeGPXpOld/f+zERn1/lKgbI0tjpsahXP5eIMPooxMHHMa0KLr/gELkp6QInyOO2lwVsoPjtjMdnjvDBs8Kbw5TIoZDPL2hXkQJu3+8QiK5fVdHQM7Ud4npKCtofSu3JzHN+UJu+2IZdER9IP4nv2MNYtmHvKwDF0P2WTK5Qmv4orlNz554=
  on:
    branch: main
